spring.application.name=BillingSoftware
server.port=${PORT:8080}

spring.datasource.username=${SDU}
spring.datasource.password=${SDP}
spring.datasource.url=${SDURL}
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/api/v1.0   

cloudflare.r2.endpoint=${CRE}
cloudflare.r2.access-key=${CRAK}
cloudflare.r2.secret-key=${CRSK}
r2.bucket.name=${RBN}
r2.public.url=${RPU}

jwt.secret.key=${JWTS}

razorpay.key.id=${RKI}
razorpay.key.secret=${RKS}


spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=16MB

